"""Se realizaron ajustes a los modelos y se creo el modelo de Logs

Revision ID: b4c0a5ccd4db
Revises: e1d36d4b48c6
Create Date: 2024-06-18 13:28:18.942572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b4c0a5ccd4db'
down_revision: Union[str, None] = 'e1d36d4b48c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ASP_PROCESS',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('script_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('script_order', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['ASP_JOBS.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['ASP_SCRIPTS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ASP_JOBS_SCRIPTS')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ASP_JOBS_SCRIPTS',
    sa.Column('id', sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('script_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ASP_JOBS.id'], name='FK__ASP_JOBS___job_i__092A4EB5'),
    sa.ForeignKeyConstraint(['script_id'], ['ASP_SCRIPTS.id'], name='FK__ASP_JOBS___scrip__0A1E72EE'),
    sa.PrimaryKeyConstraint('id', name='PK__ASP_JOBS__3213E83FC5657F9C')
    )
    op.drop_table('ASP_PROCESS')
    # ### end Alembic commands ###
