"""Se crea la tabla de Jobs

Revision ID: b7f95a819f37
Revises: 
Create Date: 2024-06-18 10:54:16.062639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7f95a819f37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ASP_JOBS_SCRIPTS',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('script_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('script_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ASP_JOBS_SCRIPTS')
    # ### end Alembic commands ###
