"""Ajustes menores

Revision ID: d2af2395f6bb
Revises: b4c0a5ccd4db
Create Date: 2024-06-18 14:58:28.331716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2af2395f6bb'
down_revision: Union[str, None] = 'b4c0a5ccd4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ASP_PROCESS', 'job_id',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    op.alter_column('ASP_PROCESS', 'script_id',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ASP_PROCESS', 'script_id',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    op.alter_column('ASP_PROCESS', 'job_id',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    # ### end Alembic commands ###
