"""Se crearon los modelos de Job, Script y la tabla intermedia que manejara la relacion de estos 2 modelos

Revision ID: e1d36d4b48c6
Revises: b7f95a819f37
Create Date: 2024-06-18 11:32:54.756556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d36d4b48c6'
down_revision: Union[str, None] = 'b7f95a819f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
import sqlmodel


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ASP_JOBS',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ASP_SCRIPTS',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ASP_JOBS_SCRIPTS', sa.Column('job_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('ASP_JOBS_SCRIPTS', sa.Column('script_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('ASP_JOBS_SCRIPTS', sa.Column('script_order', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ASP_JOBS_SCRIPTS', 'ASP_JOBS', ['job_id'], ['id'])
    op.create_foreign_key(None, 'ASP_JOBS_SCRIPTS', 'ASP_SCRIPTS', ['script_id'], ['id'])
    op.drop_column('ASP_JOBS_SCRIPTS', 'script_description')
    op.drop_column('ASP_JOBS_SCRIPTS', 'script_path')
    op.drop_column('ASP_JOBS_SCRIPTS', 'script_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ASP_JOBS_SCRIPTS', sa.Column('script_name', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('ASP_JOBS_SCRIPTS', sa.Column('script_path', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('ASP_JOBS_SCRIPTS', sa.Column('script_description', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ASP_JOBS_SCRIPTS', type_='foreignkey')
    op.drop_constraint(None, 'ASP_JOBS_SCRIPTS', type_='foreignkey')
    op.drop_column('ASP_JOBS_SCRIPTS', 'script_order')
    op.drop_column('ASP_JOBS_SCRIPTS', 'script_id')
    op.drop_column('ASP_JOBS_SCRIPTS', 'job_id')
    op.drop_table('ASP_SCRIPTS')
    op.drop_table('ASP_JOBS')
    # ### end Alembic commands ###
